### ISSUE TITLE
Error when adding `number` field

### ISSUE THREAD

**Issue by carlineng** [malloydata/malloy-composer#48]
A column named `number` appears in the available Group By fields, but adding it causes Composer to crash (see screenshot). I think its because `number` is a column in the underlying table, but its also a reserved keyword in the Malloy language. In the model file, it looks like this column is aliased, but it still shows up as a selectable column in the Composer UI, and selecting it breaks.

![image](https://user-images.githubusercontent.com/79773/202365312-52623864-a0bc-4acf-80a0-86ca852ea0d7.png)

**Comment by christopherswenson** [comment]
Thanks for writing up this issue! Yes, we have problems with quoting reserved words in the Composer at the moment. In the meantime, you should be able to rename the field in the model:

```
source: mysource is table('table-with-number-field') {
  rename: safe_number is `number`
}
```
