### ISSUE TITLE
Unhandled thrown error with invalid malloy

### ISSUE THREAD

**Issue by whscullin** [malloydata/malloy-composer#54]
Splitting out of https://github.com/malloydata/malloy-composer/issues/47, where adding fields with the same name is invalid in Malloy, but results in an unhandled exception:
![image](https://user-images.githubusercontent.com/79773/202365000-3f672f27-c018-4598-947e-cc3e485b4d11.png)

**Comment by whscullin** [comment]
Addressed by https://github.com/malloydata/malloy-composer/pull/57, could use some @tschomer love for a hero image

**Comment by tschomer** [comment]
![image](https://user-images.githubusercontent.com/40474956/206527190-5d0b9f34-c62b-4711-bf35-0950dc2ce0a4.png)

**Comment by tschomer** [comment]
![error_page](https://user-images.githubusercontent.com/40474956/206568222-49b1aa20-6f8f-415e-b87f-9eaf88fbbd33.png)
