### ISSUE TITLE
`?` in `where` breaks when loading in composer

### ISSUE THREAD

**Issue by anikaks** [malloydata/malloy-composer#64]
Loading from a readme in markdown, this query blows up the composer page and gives me an error:
```
query: sessionize is flights -> {
    where: 
      dep_time.day = @2002-03-03,
      carrier ? 'WN' | 'DL'
    group_by: flight_date is dep_time.day
    group_by: carrier
    aggregate: 
      daily_flight_count is flight_count
      aircraft.aircraft_count
    nest: per_plane_data is {
      top: 20
      group_by: tail_num
      aggregate: plane_flight_count is flight_count
      nest: flight_legs is {
        order_by: 2
        group_by:
          tail_num
          dep_minute is dep_time.minute
          origin_code
          dest_code is destination_code
          dep_delay
          arr_delay
      }
    }
  }
```

<img width="1494" alt="Screen Shot 2022-11-18 at 4 32 48 PM" src="https://user-images.githubusercontent.com/7178946/202824527-9e734601-be96-4153-a276-491462a547e1.png">

But is perfectly valid inside VS Code.

If I use `=` instead of `?` in the `carrier` filter, it works fine.

**Comment by anikaks** [comment]
This is breaking several examples, marking P1 to make sure we fix before sharing examples.

**Comment by whscullin** [comment]
This is also fixed by https://github.com/malloydata/malloy-composer/pull/69
