### ISSUE TITLE
regexp and/or contains breaking filter parsing in composer

### ISSUE THREAD

**Issue by anikaks** [malloydata/malloy-composer#65]
This breaks:
```malloy
query: stories -> term_dashboard {
  where: title ~ r'BigQuery'
}
```
<img width="1496" alt="Screen Shot 2022-11-18 at 5 09 45 PM" src="https://user-images.githubusercontent.com/7178946/202826676-792a7463-1d8d-472e-ad0c-e251171249ef.png">

Deleting the filter or filtering with an `=` loads successfully

**Comment by whscullin** [comment]
Crash is fixed by https://github.com/malloydata/malloy-composer/pull/69
