### ISSUE TITLE
Filter parsing breaks on `and`

### ISSUE THREAD

**Issue by anikaks** [malloydata/malloy-composer#66]
When attempting to load this query
```
query: stories -> posts_over_time + { 
  where: is_interesting and faang != 'OTHER'
  group_by: faang
  limit: 100000 
}
```

it breaks.
<img width="1496" alt="Screen Shot 2022-11-18 at 5 13 49 PM" src="https://user-images.githubusercontent.com/7178946/202826896-f49d5042-81ac-401e-8724-1d321e006c08.png">

If I replace `and` with `,` it's fine.

the `and` is legal in VS Code

**Comment by lloydtabb** [comment]
@whscullin @christopherswenson , if you are bored and around this one is a blocker.  Some of the models are busted because of it.  It can wait if you are out.

**Comment by whscullin** [comment]
I have a quick fix for this.
